<?php

namespace CarBundle\Repository;

/**
 * CarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarsRepository extends \Doctrine\ORM\EntityRepository
{
    public function findCars()
    {
        return $this->createQueryBuilder('c')
            ->select('c,model,make')
            ->join('c.make', 'make')
            ->join('c.model', 'model')
            ->getQuery()
            ->getResult();
    }
}
